### 카이제곱 검정(chi-squared test)

##### - 교차분석 or X^2 검정 이라고도 합니다.

In [ ]:
# 1. 데이터간의 연관성을 확인 할 때 사용
#  - 데이터간에 얼마나 가까운지에 대한 연관성 의미 부여
#  - 인과관계와는 무관함
#    인과관계 : 특정 데이터가 다른 데이터 값의 변화에 영향을 미치는지를 의미함

# 2. 카이제곱의 종류
#  - 일원카이제곱(chisquare)
#     : 1개 집단에서 기대값과 관찰값 사이의 유의미한 차이 확인
#  - 이원카이제곱(chi2_contigency)
#     : 두개 이상의 집단에서, 데이터 간의 연관성(차이) 확인
#     : 분석 대상의 집단 수에 의해서 "독립성 검정"과 "동질성 검정"으로 나뉜다.

# 1. 일원카이제곱

### exe-1) 5개의 스포츠 음료에 대한 선호도에 차이가 있는지 검정
##### - 귀무가설 : 스포츠 음료에 대한 선호도 차이가 없다
##### - 대립가설 : 스포츠 음료에 대한 선호도 차이가 있다

In [4]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
file_path = './data2/drinkdata.csv'
df = pd.read_csv(file_path)
df

음료종류  관측도수
0   s1    41
1   s2    30
2   s3    51
3   s4    71
4   s5    61

In [5]:
### 검증하기
result = stats.chisquare(df['관측도수'])

print('검정결과 = ', result)
print('검정 통계량 = %.3f, p-value = %.3f' %(result))

# (해석 - 검증결과)
# 1. p-value = 0.000 < 0.05 이므로, 귀무가설 기각
# 2. 대립가설 채택 : 스포츠 음료에 대한 선호도 차이가 있다.

검정결과 =  Power_divergenceResult(statistic=20.488188976377952, pvalue=0.00039991784008227264)
검정 통계량 = 20.488, p-value = 0.000


# 이원카이제곱 - 독립성 검정

### exe-2) 교육수준과 흡연율 간의 연관성 분석
##### - 2개 집단 : 교육수준, 흡연율
##### - 귀무가설 : 교육수준과 흡연율 간에 관련성이 없다
##### - 대립가설 : 교육수준과 흡연율 간에 관련성이 있다

In [6]:
import pandas as pd
import scipy.stats as stats

In [7]:
### 데이터 생성하기 : smoke.csv 읽어 들이기
file_path = './data2/smoke.csv'
df = pd.read_csv(file_path)
df

education  smoking
0            1        1
1            1        1
2            1        1
3            1        1
4            1        1
..         ...      ...
350          3        3
351          3        3
352          3        3
353          3        3
354          3        3

[355 rows x 2 columns]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 355 entries, 0 to 354
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   education  355 non-null    int64
 1   smoking    355 non-null    int64
dtypes: int64(2)
memory usage: 5.7 KB


In [8]:
# 각 데이터 집단간 고유한 값 확인하기
# 교육수준(education) : 1(대학원졸), 2(대졸), 3(고졸)
df['education'].unique()

array([1, 2, 3], dtype=int64)

In [9]:
# 흡연정도(smoking) : 1(골초), 2(보통), 3(노담)
df['smoking'].unique()

array([1, 2, 3], dtype=int64)

In [16]:
# 이원카이제곱은 두 집단의 교차표를 생성합니다.
# - 교차표 : 빈도 집계를 의미합니다.

ctab = pd.crosstab(index = df['education'],
                   columns = df['smoking'])
print(ctab)
print()

# 인덱스값 한글로 변경
ctab.index = ['대학원졸', '대졸', '고졸']
print(ctab)
print()

# 컬럼 인덱스값 한글로 변경
ctab.columns = ['골초', '보통', '노담']
print(ctab)

smoking     1   2   3
education            
1          51  92  68
2          22  21   9
3          43  28  21

smoking   1   2   3
대학원졸     51  92  68
대졸       22  21   9
고졸       43  28  21

      골초  보통  노담
대학원졸  51  92  68
대졸    22  21   9
고졸    43  28  21


In [17]:
# 검정
result = stats.chi2_contingency(ctab)

print('검정결과 = ', result)
print('검정 통계량 = %.3f, p-value = %.3f' %(result[0], result[1]))

# (해석 - 검증결과)
# 1. p-value=0.001 < 0.05 이므로, 귀무가설 기각
# 2. 대립가설 채택 : 교육수준과 흡연 간에는 관련이 있다.
#                  : 독립적이지 않다.

검정결과 =  (18.910915739853955, 0.0008182572832162924, 4, array([[68.94647887, 83.8056338 , 58.24788732],
       [16.9915493 , 20.65352113, 14.35492958],
       [30.06197183, 36.54084507, 25.3971831 ]]))
검정 통계량 = 18.911, p-value = 0.001


### exe-3) 국가전체와 지역에 대한 인종 간 인원수는 관련성이 있는지?
##### - 집단 2개 : 국가전체, 특정지역
##### - 귀무가설 : 국가전체와 지역에 대한 인종 간 인원수는 관련성이 없다.
##### - 대립가설 : 국가전체와 지역에 대한 인종 간 인원수는 관련성이 있다.

In [18]:
# 데이터 생성하기

# 국가전체 데이터 생성
national = pd.DataFrame(['white'] * 100000 + ['hispanic'] * 60000 + 
                        ['black'] * 5000 + ['asian'] * 15000 +
                        ['other'] * 35000)
national

0
0       white
1       white
2       white
3       white
4       white
...       ...
214995  other
214996  other
214997  other
214998  other
214999  other

[215000 rows x 1 columns]

In [19]:
la = pd.DataFrame(['white'] * 600 + ['hispanic'] * 300 + 
                        ['black'] * 250 + ['asian'] * 75 +
                        ['other'] * 150)
la

0
0     white
1     white
2     white
3     white
4     white
...     ...
1370  other
1371  other
1372  other
1373  other
1374  other

[1375 rows x 1 columns]

In [26]:
# 교차표 만들기

# 국가 전체에 대한 교차표 작성
na_table = pd.crosstab(index = national[0], columns = 'count')
print(na_table)
print()

# 특정 지역에 대한 교차표 작성
la_table = pd.crosstab(index = la[0], columns = 'count')
print(la_table)

# 두개 데이터 합치기
na_table['count_la'] = la_table['count']
na_table

col_0      count
0               
asian      15000
black       5000
hispanic   60000
other      35000
white     100000

col_0     count
0              
asian        75
black       250
hispanic    300
other       150
white       600


col_0      count  count_la
0                         
asian      15000        75
black       5000       250
hispanic   60000       300
other      35000       150
white     100000       600

In [27]:
# 검정하기
result = stats.chi2_contingency(na_table)

print('검정결과 = ', result)
print('검정 통계량 = %.3f, p-value = %.3f' %(result[0], result[1]))
# (해석)
# 1. p-value=0.000 < 0.05 이므로, 귀무가설 기각
# 2. 대립가설 채택 : 국가전체와 지역에 대한 인종 간 인원수는 관련성이 있다.

검정결과 =  (1465.1369591231146, 0.0, 4, array([[1.49792028e+04, 9.57972270e+01],
       [5.21663778e+03, 3.33622184e+01],
       [5.99168111e+04, 3.83188908e+02],
       [3.49266320e+04, 2.23367995e+02],
       [9.99607163e+04, 6.39283651e+02]]))
검정 통계량 = 1465.137, p-value = 0.000


# 이원카이제곱 - 동질성 검정

### exe-4) 교육방법에 따른 교육생들의 만족도 분석
##### - 2개 집단 : 교육방법, 만족도
##### - 귀무가설 : 교육방법에 따른 교육생들의 만족도에 차이가 없다(동질이다)
##### - 대립가설 : 교육방법에 따른 교육생들의 만족도에 차이가 있다(동질하지않다)

In [ ]:
# 데이터 생성하기

# survey_method.csv 파일 읽어 들이기

# survey 고유값 조회

# method 고유값 조회

In [28]:
import pandas as pd
import scipy.stats as stats

In [30]:
file_path = './data2/survey_method.csv'
df = pd.read_csv(file_path)
df

no  method  survey
0      1       1       1
1      2       2       2
2      3       3       3
3      4       1       4
4      5       2       5
..   ...     ...     ...
145  146       2       3
146  147       3       4
147  148       1       3
148  149       2       2
149  150       3       1

[150 rows x 3 columns]

In [32]:
# 1(매우만족), 2(만족), 3(보통), 4(불만족), 5(매우불만족)
df['survey'].unique()

array([1, 2, 3, 4, 5], dtype=int64)

In [33]:
# 1(방법1), 2(방법2), 3(방법3)
df['method'].unique()

array([1, 2, 3], dtype=int64)

In [34]:
# 교차표 작성
# - 교육방법에 대한 만족도 교차표만들기
ctab = pd.crosstab(df['method'], df['survey'])
ctab

survey  1   2   3   4  5
method                  
1       5   8  15  16  6
2       8  14  11  11  6
3       8   7  11  15  9

In [35]:
# 검정하기
result = stats.chi2_contingency(ctab)

print('검정결과 = ', result)
print('검정 통계량 = %.3f, p-value = %.3f' %(result[0], result[1]))
# (해석)
# 1. p-value=0.586 >= 0.05 이므로, 귀무가설 채택
# 2. 귀무가설 채택 : 교육방법에 따른 교육생들의 만족도에 차이가 없다.

검정결과 =  (6.544667820529891, 0.5864574374550608, 8, array([[ 7.        ,  9.66666667, 12.33333333, 14.        ,  7.        ],
       [ 7.        ,  9.66666667, 12.33333333, 14.        ,  7.        ],
       [ 7.        ,  9.66666667, 12.33333333, 14.        ,  7.        ]]))
검정 통계량 = 6.545, p-value = 0.586


### exe-5) 연령대별 sns 이용률 차이 검증
##### - 2개 집단 : 연령, sns 이용률
##### - 귀무가설 : 연령대별로 SNS 서비스 이용 현황에 차이가 없다(동질하다)
##### - 대립가설 : 연령대별로 SNS 서비스 이용 현황에 차이가 있다(동질하지않다)

In [ ]:
# 데이터 생성하기

# - snsbyage.csv 파일 읽어 들이기

# 교차표 작성

# 검증 및 해석

In [36]:
import pandas as pd
import scipy.stats as stats

In [37]:
file_path = './data2/snsbyage.csv'
df = pd.read_csv(file_path)
df

age service
0       1       F
1       1       F
2       1       F
3       1       F
4       1       F
...   ...     ...
1434    3       E
1435    3       E
1436    3       E
1437    3       E
1438    3       E

[1439 rows x 2 columns]

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1439 entries, 0 to 1438
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   age      1439 non-null   int64 
 1   service  1439 non-null   object
dtypes: int64(1), object(1)
memory usage: 22.6+ KB


In [39]:
# 1(청소년), 2(중년), 3(노년)
df['age'].unique()

array([1, 2, 3], dtype=int64)

In [40]:
df['service'].unique()

array(['F', 'T', 'K', 'C', 'E'], dtype=object)

In [46]:
ctab = pd.crosstab(df['age'], df['service'])
ctab.index = ['청소년', '중년', '노년']
ctab

service    C   E    F    K    T
청소년       81  16  207  111  117
중년       109  15  107  236  104
노년        32  17   78  133   76

In [42]:
# 검정하기
result = stats.chi2_contingency(ctab)

print('검정결과 = ', result)
print('검정 통계량 = %.3f, p-value = %.3f' %(result[0], result[1]))
# (해석)
# 1. p-value=0.000 < 0.05 이므로, 귀무가설 기각
# 2. 대립가설 채택 : 연령대별로 SNS 서비스 이용 현황에 차이가 있다(동질하지않다)

검정결과 =  (102.75202494484225, 1.1679064204212775e-18, 8, array([[ 82.07366227,  17.74565671, 144.9228631 , 177.45656706,
        109.80125087],
       [ 88.09034051,  19.04656011, 155.54690757, 190.46560111,
        117.85059069],
       [ 51.83599722,  11.20778318,  91.53022933, 112.07783183,
         69.34815844]]))
검정 통계량 = 102.752, p-value = 0.000
